version: '3.8'

services:
  dev-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: bookmark_api
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bookmark_db_dev
    networks:
      - bookmark
      
networks:
  bookmark: